logging:
    level:
        com:
            crm: debug
        org:
            springframework: warn
mybatis:
    configLocation: classpath:mybatis/mybatis-config.xml
    mapperLocations: classpath*:mapper/**/*Mapper.xml
    typeAliasesPackage: com.crm
pagehelper:
    helper-dialect: mysql
    params: count=countSql
    reasonable: true
    support-methods-arguments: true
#server:
#    port: 8089
#    servlet:
#        session:
#            timeout: 900
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        druid:
            initial-size: 1
            max-active: 20
            min-idle: 1
            stat-view-servlet:
                allow: true
            test-on-borrow: true
        password: hcs123
        url: jdbc:mysql://192.168.199.218:3306/ry?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: yzn
    redis:
        host: 127.0.0.1
        password: dsocredis
        port: 6379
        database: 10
        timeout: 5000
        jedis:
            pool:
                max-active: 8
                max-idle: 10
                max-wait: -1
                min-idle: 2


    #RabbitMQ配置
    rabbitmq:
        host: 127.0.0.1
        port: 5672
        username: admin
        password: hcs123

    session:
        store-type: redis

eureka:
    client:
        serviceUrl:
            defaultZone: http://192.168.199.217:8761/eureka/